controller_manager:
    ros__parameters:
        update_rate: 1000  # Hz

        use_sim_time: true

        position_controller:
            type: position_controllers/JointGroupPositionController

        joint_state_broadcaster:
            type: joint_state_broadcaster/JointStateBroadcaster

        velocity_controller:
            type: velocity_controllers/JointGroupVelocityController

position_controller:
    ros__parameters:
        joints:
            - base_upper_joint
            - stem1_lower_joint
            - stem2_lower_joint
            - vaccum_lower_joint
            - vaccum_base_joint
            - vaccum_joint
        interface_name: position
        command_interfaces:
            - position
        state_interfaces:
            - position
            - velocity

velocity_controller:
    ros__parameters:
        joints:
            - front_left_joint
            - front_right_joint
            - rear_left_joint
            - rear_right_joint
        interface_name: velocity
        command_interfaces:
            - velocity
        state_interfaces:
            - position
            - velocity
